export const NATIONALITIES = [
  'Afghan','Albanian','Algerian','American','Andorran','Angolan','Antiguan',
  'Argentine','Armenian','Australian','Austrian','Azerbaijani',
  'Bahamian','Bahraini','Bangladeshi','Barbadian','Belarusian','Belgian',
  'Belizean','Beninese','Bhutanese','Bolivian','Bosnian','Botswanan',
  'Brazilian','British','Bruneian','Bulgarian','Burkinabe','Burundian',
  'Cambodian','Cameroonian','Canadian','Cape Verdean','Central African',
  'Chadian','Chilean','Chinese','Colombian','Comorian','Congolese',
  'Costa Rican','Croatian','Cuban','Cypriot','Czech',
  'Danish','Djiboutian','Dominican',
  'Ecuadorian','Egyptian','Emirati','Equatorial Guinean','Eritrean',
  'Estonian','Eswatini','Ethiopian',
  'Fijian','Finnish','French',
  'Gabonese','Gambian','Georgian','German','Ghanaian','Greek','Grenadian',
  'Guatemalan','Guinean','Guinea-Bissauan','Guyanese',
  'Haitian','Honduran','Hungarian',
  'Icelandic','Indian','Indonesian','Iranian','Iraqi','Irish','Israeli',
  'Italian','Ivorian',
  'Jamaican','Japanese','Jordanian',
  'Kazakhstani','Kenyan','Kiribatian','Kuwaiti','Kyrgyzstani',
  'Laotian','Latvian','Lebanese','Lesothoan','Liberian','Libyan',
  'Liechtensteinese','Lithuanian','Luxembourgish',
  'Malagasy','Malawian','Malaysian','Maldivian','Malian','Maltese',
  'Marshallese','Mauritanian','Mauritian','Mexican','Micronesian',
  'Moldovan','Monacan','Mongolian','Montenegrin','Moroccan','Mozambican',
  'Myanmarese',
  'Namibian','Nauruan','Nepalese','New Zealander','Nicaraguan','Nigerian',
  'Nigerien','Norwegian',
  'Omani',
  'Pakistani','Palauan','Palestinian','Panamanian','Papua New Guinean',
  'Paraguayan','Peruvian','Filipino','Polish','Portuguese',
  'Qatari',
  'Romanian','Russian','Rwandan',
  'Saint Kitts and Nevisian','Saint Lucian','Saint Vincentian','Samoan',
  'San Marinese','Sao Tomean','Saudi','Senegalese','Serbian','Seychellois',
  'Sierra Leonean','Singaporean','Slovak','Slovenian','Solomon Islander',
  'Somali','South African','South Korean','South Sudanese','Spanish',
  'Sri Lankan','Sudanese','Surinamese','Swedish','Swiss','Syrian',
  'Taiwanese','Tajikistani','Tanzanian','Thai','Timorese','Togolese',
  'Tongan','Trinidadian','Tunisian','Turkish','Turkmenistani','Tuvaluan',
  'Ugandan','Ukrainian','Uruguayan','Uzbekistani',
  'Vanuatuan','Venezuelan','Vietnamese',
  'Yemeni',
  'Zambian','Zimbabwean',
]

export const POSITIONS = [
  'Master','Chief Officer','Second Officer','Chief Engineer',
  'Second Engineer','ETO','Cook','Bosun','Able Seaman','Ordinary Seaman',
]

export const CERT_TYPES = [
  'Certificate of Competency - Master (STCW II/2)',
  'Certificate of Competency - Chief Mate (STCW II/2)',
  'Certificate of Competency - OOW Navigation (STCW II/1)',
  'Certificate of Competency - Chief Engineer (STCW III/2)',
  'Certificate of Competency - Second Engineer (STCW III/2)',
  'Electro-Technical Officer Certificate (STCW III/6)',
  'STCW Basic Safety Training (VI/1)',
  'Medical Certificate (ENG1)',
  'GMDSS General Operator Certificate',
  'Advanced Fire Fighting (STCW VI/3)',
  'Proficiency in Survival Craft (STCW VI/2)',
  'ECDIS Type-Specific Certificate',
  'High Voltage Awareness Certificate',
  'Ship Cook Certificate',
  'Food Hygiene & Safety Certificate',
  'Other',
]

export const STATUSES = ['available', 'onboard', 'leave', 'inactive']
